- name: new
  hosts: localhost # when You you have to run on remote-server use name present in inventory file or use "all"
  become: true
  connection: local #Remove This when you want to run on remote server
  tasks:
    - name: update apt
      shell: apt update -y

    - name: install LEMP
      apt:
        name: "{{ item }}"
        state: present
      with_items:
         - nginx
         - php
         - php8.3-fpm
         - mariadb-server

    - name: start LEMP
      service:
        name: "{{ item }}"
        state: started
      with_items:
         - nginx
         - php8.3-fpm
         - mariadb
    
